#!/usr/bin/env python
import pushycat.config
import argparse

def add(url, branch, directory, user):
    """Adds a webhook listener to the configuration file"""

    conf = pushycat.config.Config()

    conf.add(url, branch, directory, user)

    print("webhook succesfully added.")
    print("Please restart pushycat (service pushycat restart)")


def main():
    parser = argparse.ArgumentParser(
            description='Adds a hook to pushycat that automatically updates your repository.')

    parser.add_argument('url')
    parser.add_argument('directory')
    parser.add_argument('user')
    parser.add_argument('--branch', default='master')

    options = parser.parse_args()
    add(options.url, options.branch, options.directory, options.user)

if __name__ == "__main__":
    main()
