#!/usr/bin/env python

import pushycat.config
import pushycat.http_listener
import pushycat.client
import os
import pwd
import sys

def setup(conf):
    """Configure clients and http listener"""

    clients = {}
    listener = pushycat.http_listener.HttpListener(conf.listen(), conf.path())

    for hook in conf.hooks():
        user       = hook["user"]
        repository = hook["repository"]
        branch     = hook["branch"]
        run        = hook["run"]

        c = clients.get(user, None)
        if c is None:
            c = clients[user] = pushycat.client.Client(user, os.pipe())

        c.add(repository, branch, run)
        listener.add(
                repository,
                branch,
                lambda sha, c=c, r=repository, b=branch: c.notify(r, b, sha))

    return (listener, clients.values())


def chuser(username):
    """Change the uid/gid of the current process to that of given the username"""
    uid = pwd.getpwnam(username).pw_uid

    if uid != 0:
        os.setgid(uid)
        os.setuid(uid)


def run():
    """Launch webserver and clients, and wait forever"""

    conf = pushycat.config.Config()

    listener, clients = setup(conf)

    if os.fork() == 0:
        chuser(conf.user())
        listener.run()
        sys.exit(-1)

    for client in clients:
        if os.fork() == 0:
            chuser(client.user)
            client.run()
            sys.exit(-1)

    for i in range(0, 1 + len(clients)):
        os.wait()

if __name__ == "__main__":
    run()
