#!/bin/sh

set -e
. /usr/share/debconf/confmodule

case "$1" in
  configure)

	if ! getent passwd pushycat > /dev/null ; then
	  echo 'Adding system-user for pushycat' 1>&2
	  adduser --system --group --quiet --home /etc/pushycat \
	    --no-create-home --disabled-login --force-badname pushycat
	fi
  ;;
esac
